include_guard(GLOBAL)

include(CPM)
cpm(SYSTEM SHALLOW PROGRESS EXCLUDE_FROM_ALL)

if(NOT DEFINED CPP-TERMINAL_REPOSITORY)
  set(CPP-TERMINAL_REPOSITORY "https://github.com/jupyter-xeus/cpp-terminal.git")
endif()

if(NOT DEFINED CPP-TERMINAL_TAG)
  set(CPP-TERMINAL_TAG "master")
endif()

CPMAddPackage(NAME cpp-terminal
               GIT_REPOSITORY "${CPP-TERMINAL_REPOSITORY}"
               GIT_TAG "${CPP-TERMINAL_TAG}"
              OPTIONS "CPPTERMINAL_BUILD_EXAMPLES FALSE" "CPPTERMINAL_ENABLE_INSTALL ON" "CPPTERMINAL_ENABLE_TESTING OFF" "CPPTERMINAL_ENABLE_DOCS OFF")
