include_guard(GLOBAL)

include(CPM)
cpm(SYSTEM SHALLOW PROGRESS EXCLUDE_FROM_ALL)

if(NOT DEFINED DOCTEST_REPOSITORY)
  set(DOCTEST_REPOSITORY "https://github.com/doctest/doctest.git")
endif()

if(NOT DEFINED DOCTEST_TAG)
  set(DOCTEST_TAG "v2.5.2")
endif()

CPMAddPackage(NAME doctest
              GIT_SHALLOW TRUE
              GIT_REPOSITORY "${DOCTEST_REPOSITORY}"
              GIT_TAG "${DOCTEST_TAG}"
              OPTIONS "CPPTERMINAL_BUILD_EXAMPLES FALSE" "CPPTERMINAL_ENABLE_INSTALL ON" "CPPTERMINAL_ENABLE_TESTING OFF" "CPPTERMINAL_ENABLE_DOCS OFF")
