name: 'MacOS Clang'

on:
  push:
    branches:
      - main
    paths:
      - '!docs/**'
      - '!.github/workflows/**'
      - '.github/workflows/MacOS-Clang.yml'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: '🚧 🟨 Clang'

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3

      - name: '📥 Load .env file'
        if: hashFiles('.github/workflows/.env') != ''
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows

      - name: '🟨 Setup CMake'
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '${{env.CMAKE_VERSION}}'
          github-api-token: ${{ secrets.GITHUB_TOKEN }}

      - name: '🍺 Install packages with brew'
        if: ${{ env.INSTALL_PACKAGES != '' }}
        run: brew install ${{env.INSTALL_PACKAGES}}

      - name: '🔧 Configure'
        run: cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_PREFIX }} -D CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}  -DBUILD_TESTS=${{ env.BUILD_TESTS }} -DBUILD_DOCS=${{ env.BUILD_DOCS }} -DBUILD_EXAMPLES=${{ env.BUILD_EXAMPLES }}

      - name: '⚙️ Build'
        run: cmake --build ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --parallel ${{ env.CMAKE_NUMBER_JOBS }}

      - name: '🧪 Run tests'
        working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
        run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} --parallel ${{ env.CMAKE_NUMBER_JOBS_TESTS }} -VV --output-on-failure
