name: 'Windows MSYS2'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟨', sys: mingw32, env: i686, name: MINGW32 }
          - { icon: '🟦', sys: mingw64, env: x86_64, name: MINGW64 }
          - { icon: '🟩', sys: ucrt64,  env: ucrt-x86_64, name: UCRT64 }  # Experimental!
          - { icon: '🟥', sys: clang64, env: clang-x86_64, name: Clang64 } # Experimental!

    name: '🚧 ${{ matrix.icon }} ${{ matrix.name }}'
    defaults:
      run:
        shell: msys2 {0}

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v2.4.0

      - name: '📥 Load .env file'
        if: hashFiles('.github/workflows/.env') != ''
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          path-type: minimal
          release: true
          update: true
          install: >-
            git
          pacboy: >-
            cmake:p
            ninja:p
            make:p
            ${{env.INSTALL_PACKAGES}}
            
      - name: '🔧 Configure'
        run: cmake -S . -B ${{ env.CMAKE_BUILD_PREFIX }} -D CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}  -DBUILD_TESTS=${{ env.BUILD_TESTS }} -DBUILD_DOCS=${{ env.BUILD_DOCS }} -DBUILD_EXAMPLES=${{ env.BUILD_EXAMPLES }}

      - name: '⚙️ Build'
        run: cmake --build ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --parallel ${{ env.CMAKE_NUMBER_JOBS }}

      - name: '🧪 Run tests'
        working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
        run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} --parallel ${{ env.CMAKE_NUMBER_JOBS_TESTS }} -VV --output-on-failure
